// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nwdyzzxuakkrtoantsta.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53ZHl6enh1YWtrcnRvYW50c3RhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3ODM2NDQsImV4cCI6MjA3MjM1OTY0NH0.Fom2rYqjgErJszqN5nWVfBp9pwQkBsQUpo3vPddAurY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});